apiVersion: v2
name: seer
description: A Helm chart for Kubernetes

type: application

version: 3.1.0 

appVersion: "latest"

dependencies:
- name: seer
  version: 3.1.0
  repository: https://github.com/seerr-team/seerr/tree/main/charts/seerr