apiVersion: v2
name: seer
description: A Helm chart for Kubernetes

type: application

version: 3.1.0 

appVersion: 'v3.0.1'

dependencies:
- name: seer
  version: 3.1.0
  repository: oci://ghcr.io/seerr-team/seerr/seerr-chart