replicaCount: 1
name: seerr
targetPort: 80

seerr-chart:
  image:
    registry: ghcr.io
    repository: seerr-team/seerr
    pullPolicy: IfNotPresent  
  serviceAccount:
    create: true
    automount: true
  config:
    persistence:
      size: 1Gi
      annotations:
        - storageClassName: synology-csi-iscsi-delete
      accessModes:
        - ReadWriteOnce
      existingClaim: 'overseerr-pvc'
  service:
    type: ClusterIP
    port: 80
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      external-dns.alpha.kubernetes.io/host: seerr.frost.haus
    hosts:
      - host: seerr.frost.haus
        http:
          paths:
          - pathType: ImplementationSpecific
            path: "/"
            backend:
              service:
                name: seerr
                port:
                  name: http
    tls:
      - hosts:
        - seerr.frost.haus
        secretName: seerr-cert