replicaCount: 1
name: seerr
targetPort: 80

seerr-chart:
  image:
    registry: ghcr.io
    repository: seerr-team/seerr
    pullPolicy: IfNotPresent  
  serviceAccount:
    create: true
    automount: true
  config:
    persistence:
      size: 1Gi
      annotations:
        - storageClassName: synology-csi-iscsi-delete
      accessModes:
        - ReadWriteOnce
      existingClaim: 'overseerr-pvc'
      name: 'overseerr-pvc'
      volumeName: 'pvc-02639796-8217-461b-866a-efed822b10d3'
  service:
    type: ClusterIP
    port: 80
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      external-dns.alpha.kubernetes.io/host: seerr.frost.haus
    hosts:
      - host: seerr.frost.haus
        paths:
        - pathType: ImplementationSpecific
          path: "/"
    tls:
      - hosts:
        - seerr.frost.haus
        secretName: seerr-cert