apiVersion: v2
name: reloader
description: Stakater Reloader for automatic pod restarts on ConfigMap/Secret changes
type: application
version: 1.0.0
appVersion: "v1.2.0"
dependencies:
  - name: reloader
    version: 1.2.0
    repository: https://stakater.github.io/stakater-charts
