apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: overseerr
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    external-dns.alpha.kubernetes.io/host: overseerr.frost.haus
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - overseerr.frost.haus
    secretName: overseerr-cert
  rules:
  - host: overseerr.frost.haus
    http:
      paths:
      - pathType: ImplementationSpecific
        path: "/"
        backend:
          service:
            name: overseerr
            port:
              name: http
