apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: overseerr-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: synology-csi-iscsi-delete
  volumeName: pvc-02639796-8217-461b-866a-efed822b10d3
  resources:
    requests:
      storage: 1Gi