name: headlamp
# targetPort: 8989
# puid: 1026
# pgid: 100
headlamp:
  replicaCount: 1
  pluginsManager:
    enabled: "true"
    configContent: |
      plugins:
        - name: ai-assistant
          source: https://github.com/headlamp-k8s/plugins/blob/main/ai-assistant/
          version: "0.1.0-alpha"
      installOptions:
        parallel: true
        maxConcurrent: 2  
    config:
      enableHelm: "true"
      watchPlugins: "true"
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      external-dns.alpha.kubernetes.io/host: headlamp.frost.haus    
    ingressClassName: nginx
    hosts:
      - host: headlamp.frost.haus
        paths:
          - type: ImplementationSpecific
            path: "/"
            backend:
              service:
                name: headlamp
                port:
                  number: 80
    tls: 
      - hosts:
        - headlamp.frost.haus
        secretName: headlamp-cert
  persistentVolumeClaim:
    enabled: true
    size: 2Gi
    storageClassName: synology-csi-iscsi-delete
    accessModes: 
      - ReadWriteOnce