---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.name }}-secrets
  namespace: {{ .Values.name }}
spec:
  encryptedData:
    sonarr_url: PLACEHOLDER_SONARR_URL
    sonarr_api_key: PLACEHOLDER_SONARR_API_KEY
    radarr_url: PLACEHOLDER_RADARR_URL
    radarr_api_key: PLACEHOLDER_RADARR_API_KEY
  template:
    metadata:
      name: {{ .Values.name }}-secrets
      namespace: {{ .Values.name }}
    type: Opaque
