apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.name }}
spec:
  strategy:
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      annotations:
        reloader.stakater.com/auto: "true"
      labels:
        app: {{ .Values.name }}
        app.kubernetes.io/name: {{ .Values.name }}
    spec:
      serviceAccountName: homepage
      automountServiceAccountToken: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      containers:
      - name: {{ .Values.name }}
        image: "ghcr.io/gethomepage/homepage:latest"
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.targetPort }}
        env:
        - name: HOMEPAGE_VAR_ARGOCD_APIKEY
          valueFrom:
            secretKeyRef:
              name: homepage-secrets
              key:  argocd_apikey
        - name: HOMEPAGE_VAR_BAZARR_APIKEY
          valueFrom:
            secretKeyRef:
              name: homepage-secrets
              key:  bazarr_apikey
        - name: HOMEPAGE_VAR_DNS1_APIKEY
          valueFrom:
            secretKeyRef:
              name: homepage-secrets
              key:  dns1_apikey              
        - name: HOMEPAGE_VAR_DNS2_APIKEY
          valueFrom:
            secretKeyRef:
              name: homepage-secrets
              key:  dns2_apikey              
        - name: HOMEPAGE_VAR_HOMEASSISTANT_APIKEY
          valueFrom:
            secretKeyRef:
              name: homepage-secrets
              key:  homeassistant_apikey              
        - name: HOMEPAGE_VAR_OVERSEERR_APIKEY
          valueFrom:
            secretKeyRef:
              name: homepage-secrets
              key:  overseerr_apikey              
        - name: HOMEPAGE_VAR_NETDATA_APIKEY
          valueFrom:
            secretKeyRef:
              name: homepage-secrets
              key:  netdata_apikey              
        - name: HOMEPAGE_VAR_PBS_APIKEY
          valueFrom:
            secretKeyRef:
              name: homepage-secrets
              key:  pbs_apikey                          
        - name: HOMEPAGE_VAR_PORTAINER_APIKEY
          valueFrom:
            secretKeyRef:
              name: homepage-secrets
              key:  portainer_apikey              
        - name: HOMEPAGE_VAR_PROWLARR_APIKEY
          valueFrom:
            secretKeyRef:
              name: homepage-secrets
              key:  prowlarr_apikey              
        - name: HOMEPAGE_VAR_PVE_APIKEY
          valueFrom:
            secretKeyRef:
              name: homepage-secrets
              key:  pve_apikey              
        - name: HOMEPAGE_VAR_RADARR_APIKEY
          valueFrom:
            secretKeyRef:
              name: homepage-secrets
              key:  radarr_apikey              
        - name: HOMEPAGE_VAR_SABNZBD_APIKEY
          valueFrom:
            secretKeyRef:
              name: homepage-secrets
              key:  sabnzbd_apikey              
        - name: HOMEPAGE_VAR_SONARR_APIKEY
          valueFrom:
            secretKeyRef:
              name: homepage-secrets
              key:  sonarr_apikey              
        - name: HOMEPAGE_VAR_TAUTULLI_APIKEY
          valueFrom:
            secretKeyRef:
              name: homepage-secrets
              key:  tautulli_apikey              
        - name: HOMEPAGE_VAR_PLEX_APIKEY
          valueFrom:
            secretKeyRef:
              name: homepage-secrets
              key:  x-plex-token
        - name: HOMEPAGE_ALLOWED_HOSTS
          value: homepage.frost.haus, frost.haus, localhost
        volumeMounts:
        - mountPath: /app/config/custom.js
          name: homepage-config
          subPath: custom.js
        - mountPath: /app/config/proxmox.yaml
          name: homepage-config
          subPath: custom.js
        - mountPath: /app/config/custom.css
          name: homepage-config
          subPath: custom.css
        - mountPath: /app/config/bookmarks.yaml
          name: homepage-config
          subPath: bookmarks.yaml
        - mountPath: /app/config/docker.yaml
          name: homepage-config
          subPath: docker.yaml
        - mountPath: /app/config/kubernetes.yaml
          name: homepage-config
          subPath: kubernetes.yaml
        - mountPath: /app/config/services.yaml
          name: homepage-config
          subPath: services.yaml
        - mountPath: /app/config/settings.yaml
          name: homepage-config
          subPath: settings.yaml
        - mountPath: /app/config/widgets.yaml
          name: homepage-config
          subPath: widgets.yaml
        - mountPath: /app/config/logs
          name: logs
      volumes:
      - name: homepage-config
        configMap:
          name: homepage
      - name: logs
        emptyDir: {}
